export enum EnvironmentEnums {
    SERVICE_TWILIO_ACCOUNT_SID = 'SERVICE_TWILIO_ACCOUNT_SID',
    SERVICE_TWILIO_KEY_SID = 'SERVICE_TWILIO_KEY_SID',
    SERVICE_TWILIO_KEY_SECRET = 'SERVICE_TWILIO_KEY_SECRET',
    SERVICE_TWILIO_CONVERSATION_SID = 'SERVICE_TWILIO_CONVERSATION_SID',
    SERVICE_TWILIO_MESSAGING_SID = 'SERVICE_TWILIO_MESSAGING_SID',
    APPLICATION_ENDPOINT = 'APPLICATION_ENDPOINT',
    GCP_DF_PROJECT_ID = 'GCP_DF_PROJECT_ID',
    GCP_DF_PRIVATE_KEY = 'GCP_DF_PRIVATE_KEY',
    GCP_DF_CLIENT_EMAIL = 'GCP_DF_CLIENT_EMAIL',
}
